-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity poseidon_top_poseidon_top_Pipeline_VITIS_LOOP_92_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    p_0_0_01942 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_144 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_246 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_348 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_450 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_552 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_654 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_756 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_858 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_960 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1062 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1164 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1266 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1368 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1470 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1572 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1674 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1776 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1878 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_1980 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_2082 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_2184 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_2286 : IN STD_LOGIC_VECTOR (255 downto 0);
    p_0_0_011_2388 : IN STD_LOGIC_VECTOR (255 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    out_stream_TVALID : OUT STD_LOGIC );
end;


architecture behav of poseidon_top_poseidon_top_Pipeline_VITIS_LOOP_92_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln92_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_val_data_fu_311_p51 : STD_LOGIC_VECTOR (255 downto 0);
    signal out_val_data_reg_453 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal out_val_last_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_val_last_reg_458 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_fu_136 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln92_fu_305_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal out_val_data_fu_311_p49 : STD_LOGIC_VECTOR (255 downto 0);
    signal or_ln_fu_426_p4 : STD_LOGIC_VECTOR (288 downto 0);
    signal sext_ln98_fu_434_p1 : STD_LOGIC_VECTOR (319 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal out_val_data_fu_311_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_val_data_fu_311_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component poseidon_top_sparsemux_49_5_256_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (4 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (4 downto 0);
        din23_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (255 downto 0);
        din1 : IN STD_LOGIC_VECTOR (255 downto 0);
        din2 : IN STD_LOGIC_VECTOR (255 downto 0);
        din3 : IN STD_LOGIC_VECTOR (255 downto 0);
        din4 : IN STD_LOGIC_VECTOR (255 downto 0);
        din5 : IN STD_LOGIC_VECTOR (255 downto 0);
        din6 : IN STD_LOGIC_VECTOR (255 downto 0);
        din7 : IN STD_LOGIC_VECTOR (255 downto 0);
        din8 : IN STD_LOGIC_VECTOR (255 downto 0);
        din9 : IN STD_LOGIC_VECTOR (255 downto 0);
        din10 : IN STD_LOGIC_VECTOR (255 downto 0);
        din11 : IN STD_LOGIC_VECTOR (255 downto 0);
        din12 : IN STD_LOGIC_VECTOR (255 downto 0);
        din13 : IN STD_LOGIC_VECTOR (255 downto 0);
        din14 : IN STD_LOGIC_VECTOR (255 downto 0);
        din15 : IN STD_LOGIC_VECTOR (255 downto 0);
        din16 : IN STD_LOGIC_VECTOR (255 downto 0);
        din17 : IN STD_LOGIC_VECTOR (255 downto 0);
        din18 : IN STD_LOGIC_VECTOR (255 downto 0);
        din19 : IN STD_LOGIC_VECTOR (255 downto 0);
        din20 : IN STD_LOGIC_VECTOR (255 downto 0);
        din21 : IN STD_LOGIC_VECTOR (255 downto 0);
        din22 : IN STD_LOGIC_VECTOR (255 downto 0);
        din23 : IN STD_LOGIC_VECTOR (255 downto 0);
        def : IN STD_LOGIC_VECTOR (255 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (255 downto 0) );
    end component;


    component poseidon_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_49_5_256_1_1_U194 : component poseidon_top_sparsemux_49_5_256_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 256,
        CASE1 => "00001",
        din1_WIDTH => 256,
        CASE2 => "00010",
        din2_WIDTH => 256,
        CASE3 => "00011",
        din3_WIDTH => 256,
        CASE4 => "00100",
        din4_WIDTH => 256,
        CASE5 => "00101",
        din5_WIDTH => 256,
        CASE6 => "00110",
        din6_WIDTH => 256,
        CASE7 => "00111",
        din7_WIDTH => 256,
        CASE8 => "01000",
        din8_WIDTH => 256,
        CASE9 => "01001",
        din9_WIDTH => 256,
        CASE10 => "01010",
        din10_WIDTH => 256,
        CASE11 => "01011",
        din11_WIDTH => 256,
        CASE12 => "01100",
        din12_WIDTH => 256,
        CASE13 => "01101",
        din13_WIDTH => 256,
        CASE14 => "01110",
        din14_WIDTH => 256,
        CASE15 => "01111",
        din15_WIDTH => 256,
        CASE16 => "10000",
        din16_WIDTH => 256,
        CASE17 => "10001",
        din17_WIDTH => 256,
        CASE18 => "10010",
        din18_WIDTH => 256,
        CASE19 => "10011",
        din19_WIDTH => 256,
        CASE20 => "10100",
        din20_WIDTH => 256,
        CASE21 => "10101",
        din21_WIDTH => 256,
        CASE22 => "10110",
        din22_WIDTH => 256,
        CASE23 => "10111",
        din23_WIDTH => 256,
        def_WIDTH => 256,
        sel_WIDTH => 5,
        dout_WIDTH => 256)
    port map (
        din0 => p_0_0_01942,
        din1 => p_0_0_011_144,
        din2 => p_0_0_011_246,
        din3 => p_0_0_011_348,
        din4 => p_0_0_011_450,
        din5 => p_0_0_011_552,
        din6 => p_0_0_011_654,
        din7 => p_0_0_011_756,
        din8 => p_0_0_011_858,
        din9 => p_0_0_011_960,
        din10 => p_0_0_011_1062,
        din11 => p_0_0_011_1164,
        din12 => p_0_0_011_1266,
        din13 => p_0_0_011_1368,
        din14 => p_0_0_011_1470,
        din15 => p_0_0_011_1572,
        din16 => p_0_0_011_1674,
        din17 => p_0_0_011_1776,
        din18 => p_0_0_011_1878,
        din19 => p_0_0_011_1980,
        din20 => p_0_0_011_2082,
        din21 => p_0_0_011_2184,
        din22 => p_0_0_011_2286,
        din23 => p_0_0_011_2388,
        def => out_val_data_fu_311_p49,
        sel => ap_sig_allocacmp_i,
        dout => out_val_data_fu_311_p51);

    flow_control_loop_pipe_sequential_init_U : component poseidon_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln92_fu_299_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_1_fu_136 <= add_ln92_fu_305_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_136 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                out_val_data_reg_453 <= out_val_data_fu_311_p51;
                out_val_last_reg_458 <= out_val_last_fu_415_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln92_fu_305_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, out_stream_TREADY, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((out_stream_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, out_stream_TREADY, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((out_stream_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(out_stream_TREADY)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (out_stream_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln92_fu_299_p2)
    begin
        if (((icmp_ln92_fu_299_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_1_fu_136, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i <= i_1_fu_136;
        end if; 
    end process;

    icmp_ln92_fu_299_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv5_18) else "0";
    or_ln_fu_426_p4 <= ((ap_const_lv32_80000000 & out_val_last_reg_458) & out_val_data_reg_453);
    out_stream_TDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln98_fu_434_p1),512));

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, out_stream_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_stream_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    out_val_data_fu_311_p49 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    out_val_last_fu_415_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv5_17) else "0";
        sext_ln98_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln_fu_426_p4),320));

end behav;
