// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module poseidon_top_poseidon_top_Pipeline_VITIS_LOOP_92_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_stream_TREADY,
        p_0_0_01942,
        p_0_0_011_144,
        p_0_0_011_246,
        p_0_0_011_348,
        p_0_0_011_450,
        p_0_0_011_552,
        p_0_0_011_654,
        p_0_0_011_756,
        p_0_0_011_858,
        p_0_0_011_960,
        p_0_0_011_1062,
        p_0_0_011_1164,
        p_0_0_011_1266,
        p_0_0_011_1368,
        p_0_0_011_1470,
        p_0_0_011_1572,
        p_0_0_011_1674,
        p_0_0_011_1776,
        p_0_0_011_1878,
        p_0_0_011_1980,
        p_0_0_011_2082,
        p_0_0_011_2184,
        p_0_0_011_2286,
        p_0_0_011_2388,
        out_stream_TDATA,
        out_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_stream_TREADY;
input  [255:0] p_0_0_01942;
input  [255:0] p_0_0_011_144;
input  [255:0] p_0_0_011_246;
input  [255:0] p_0_0_011_348;
input  [255:0] p_0_0_011_450;
input  [255:0] p_0_0_011_552;
input  [255:0] p_0_0_011_654;
input  [255:0] p_0_0_011_756;
input  [255:0] p_0_0_011_858;
input  [255:0] p_0_0_011_960;
input  [255:0] p_0_0_011_1062;
input  [255:0] p_0_0_011_1164;
input  [255:0] p_0_0_011_1266;
input  [255:0] p_0_0_011_1368;
input  [255:0] p_0_0_011_1470;
input  [255:0] p_0_0_011_1572;
input  [255:0] p_0_0_011_1674;
input  [255:0] p_0_0_011_1776;
input  [255:0] p_0_0_011_1878;
input  [255:0] p_0_0_011_1980;
input  [255:0] p_0_0_011_2082;
input  [255:0] p_0_0_011_2184;
input  [255:0] p_0_0_011_2286;
input  [255:0] p_0_0_011_2388;
output  [511:0] out_stream_TDATA;
output   out_stream_TVALID;

reg ap_idle;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln92_fu_299_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire   [255:0] out_val_data_fu_311_p51;
reg   [255:0] out_val_data_reg_453;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] out_val_last_fu_415_p2;
reg   [0:0] out_val_last_reg_458;
reg   [4:0] i_1_fu_136;
wire   [4:0] add_ln92_fu_305_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i;
reg    ap_block_pp0_stage0_01001;
wire   [255:0] out_val_data_fu_311_p49;
wire   [288:0] or_ln_fu_426_p4;
wire  signed [319:0] sext_ln98_fu_434_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [4:0] out_val_data_fu_311_p1;
wire   [4:0] out_val_data_fu_311_p3;
wire   [4:0] out_val_data_fu_311_p5;
wire   [4:0] out_val_data_fu_311_p7;
wire   [4:0] out_val_data_fu_311_p9;
wire   [4:0] out_val_data_fu_311_p11;
wire   [4:0] out_val_data_fu_311_p13;
wire   [4:0] out_val_data_fu_311_p15;
wire   [4:0] out_val_data_fu_311_p17;
wire   [4:0] out_val_data_fu_311_p19;
wire   [4:0] out_val_data_fu_311_p21;
wire   [4:0] out_val_data_fu_311_p23;
wire   [4:0] out_val_data_fu_311_p25;
wire   [4:0] out_val_data_fu_311_p27;
wire   [4:0] out_val_data_fu_311_p29;
wire   [4:0] out_val_data_fu_311_p31;
wire  signed [4:0] out_val_data_fu_311_p33;
wire  signed [4:0] out_val_data_fu_311_p35;
wire  signed [4:0] out_val_data_fu_311_p37;
wire  signed [4:0] out_val_data_fu_311_p39;
wire  signed [4:0] out_val_data_fu_311_p41;
wire  signed [4:0] out_val_data_fu_311_p43;
wire  signed [4:0] out_val_data_fu_311_p45;
wire  signed [4:0] out_val_data_fu_311_p47;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_1_fu_136 = 5'd0;
#0 ap_done_reg = 1'b0;
end

poseidon_top_sparsemux_49_5_256_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 256 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 256 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 256 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 256 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 256 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 256 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 256 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 256 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 256 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 256 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 256 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 256 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 256 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 256 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 256 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 256 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 256 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 256 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 256 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 256 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 256 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 256 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 256 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 256 ),
    .def_WIDTH( 256 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 256 ))
sparsemux_49_5_256_1_1_U194(
    .din0(p_0_0_01942),
    .din1(p_0_0_011_144),
    .din2(p_0_0_011_246),
    .din3(p_0_0_011_348),
    .din4(p_0_0_011_450),
    .din5(p_0_0_011_552),
    .din6(p_0_0_011_654),
    .din7(p_0_0_011_756),
    .din8(p_0_0_011_858),
    .din9(p_0_0_011_960),
    .din10(p_0_0_011_1062),
    .din11(p_0_0_011_1164),
    .din12(p_0_0_011_1266),
    .din13(p_0_0_011_1368),
    .din14(p_0_0_011_1470),
    .din15(p_0_0_011_1572),
    .din16(p_0_0_011_1674),
    .din17(p_0_0_011_1776),
    .din18(p_0_0_011_1878),
    .din19(p_0_0_011_1980),
    .din20(p_0_0_011_2082),
    .din21(p_0_0_011_2184),
    .din22(p_0_0_011_2286),
    .din23(p_0_0_011_2388),
    .def(out_val_data_fu_311_p49),
    .sel(ap_sig_allocacmp_i),
    .dout(out_val_data_fu_311_p51)
);

poseidon_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln92_fu_299_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_136 <= add_ln92_fu_305_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_136 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_val_data_reg_453 <= out_val_data_fu_311_p51;
        out_val_last_reg_458 <= out_val_last_fu_415_p2;
    end
end

always @ (*) begin
    if (((icmp_ln92_fu_299_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 5'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln92_fu_305_p2 = (ap_sig_allocacmp_i + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((out_stream_TREADY == 1'b0) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((out_stream_TREADY == 1'b0) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (out_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln92_fu_299_p2 = ((ap_sig_allocacmp_i == 5'd24) ? 1'b1 : 1'b0);

assign or_ln_fu_426_p4 = {{{{32'd2147483648}, {out_val_last_reg_458}}}, {out_val_data_reg_453}};

assign out_stream_TDATA = $unsigned(sext_ln98_fu_434_p1);

assign out_val_data_fu_311_p49 = 'bx;

assign out_val_last_fu_415_p2 = ((ap_sig_allocacmp_i == 5'd23) ? 1'b1 : 1'b0);

assign sext_ln98_fu_434_p1 = $signed(or_ln_fu_426_p4);

endmodule //poseidon_top_poseidon_top_Pipeline_VITIS_LOOP_92_3
