// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module poseidon_top_poseidon_top_Pipeline_VITIS_LOOP_42_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        in_stream_TDATA,
        in_stream_TREADY,
        arrayidx11_23_promoted103_out,
        arrayidx11_23_promoted103_out_ap_vld,
        arrayidx11_22_promoted101_out,
        arrayidx11_22_promoted101_out_ap_vld,
        arrayidx11_21_promoted99_out,
        arrayidx11_21_promoted99_out_ap_vld,
        arrayidx11_20_promoted97_out,
        arrayidx11_20_promoted97_out_ap_vld,
        arrayidx11_19_promoted95_out,
        arrayidx11_19_promoted95_out_ap_vld,
        arrayidx11_18_promoted93_out,
        arrayidx11_18_promoted93_out_ap_vld,
        arrayidx11_17_promoted91_out,
        arrayidx11_17_promoted91_out_ap_vld,
        arrayidx11_16_promoted89_out,
        arrayidx11_16_promoted89_out_ap_vld,
        arrayidx11_15_promoted87_out,
        arrayidx11_15_promoted87_out_ap_vld,
        arrayidx11_14_promoted85_out,
        arrayidx11_14_promoted85_out_ap_vld,
        arrayidx11_13_promoted83_out,
        arrayidx11_13_promoted83_out_ap_vld,
        arrayidx11_12_promoted81_out,
        arrayidx11_12_promoted81_out_ap_vld,
        arrayidx11_11_promoted79_out,
        arrayidx11_11_promoted79_out_ap_vld,
        arrayidx11_10_promoted77_out,
        arrayidx11_10_promoted77_out_ap_vld,
        arrayidx11_9_promoted75_out,
        arrayidx11_9_promoted75_out_ap_vld,
        arrayidx11_8_promoted73_out,
        arrayidx11_8_promoted73_out_ap_vld,
        arrayidx11_7_promoted71_out,
        arrayidx11_7_promoted71_out_ap_vld,
        arrayidx11_6_promoted69_out,
        arrayidx11_6_promoted69_out_ap_vld,
        arrayidx11_5_promoted67_out,
        arrayidx11_5_promoted67_out_ap_vld,
        arrayidx11_4_promoted65_out,
        arrayidx11_4_promoted65_out_ap_vld,
        arrayidx11_3_promoted63_out,
        arrayidx11_3_promoted63_out_ap_vld,
        arrayidx11_2_promoted61_out,
        arrayidx11_2_promoted61_out_ap_vld,
        arrayidx11_1_promoted59_out,
        arrayidx11_1_promoted59_out_ap_vld,
        arrayidx82_promoted57_out,
        arrayidx82_promoted57_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input  [511:0] in_stream_TDATA;
output   in_stream_TREADY;
output  [255:0] arrayidx11_23_promoted103_out;
output   arrayidx11_23_promoted103_out_ap_vld;
output  [255:0] arrayidx11_22_promoted101_out;
output   arrayidx11_22_promoted101_out_ap_vld;
output  [255:0] arrayidx11_21_promoted99_out;
output   arrayidx11_21_promoted99_out_ap_vld;
output  [255:0] arrayidx11_20_promoted97_out;
output   arrayidx11_20_promoted97_out_ap_vld;
output  [255:0] arrayidx11_19_promoted95_out;
output   arrayidx11_19_promoted95_out_ap_vld;
output  [255:0] arrayidx11_18_promoted93_out;
output   arrayidx11_18_promoted93_out_ap_vld;
output  [255:0] arrayidx11_17_promoted91_out;
output   arrayidx11_17_promoted91_out_ap_vld;
output  [255:0] arrayidx11_16_promoted89_out;
output   arrayidx11_16_promoted89_out_ap_vld;
output  [255:0] arrayidx11_15_promoted87_out;
output   arrayidx11_15_promoted87_out_ap_vld;
output  [255:0] arrayidx11_14_promoted85_out;
output   arrayidx11_14_promoted85_out_ap_vld;
output  [255:0] arrayidx11_13_promoted83_out;
output   arrayidx11_13_promoted83_out_ap_vld;
output  [255:0] arrayidx11_12_promoted81_out;
output   arrayidx11_12_promoted81_out_ap_vld;
output  [255:0] arrayidx11_11_promoted79_out;
output   arrayidx11_11_promoted79_out_ap_vld;
output  [255:0] arrayidx11_10_promoted77_out;
output   arrayidx11_10_promoted77_out_ap_vld;
output  [255:0] arrayidx11_9_promoted75_out;
output   arrayidx11_9_promoted75_out_ap_vld;
output  [255:0] arrayidx11_8_promoted73_out;
output   arrayidx11_8_promoted73_out_ap_vld;
output  [255:0] arrayidx11_7_promoted71_out;
output   arrayidx11_7_promoted71_out_ap_vld;
output  [255:0] arrayidx11_6_promoted69_out;
output   arrayidx11_6_promoted69_out_ap_vld;
output  [255:0] arrayidx11_5_promoted67_out;
output   arrayidx11_5_promoted67_out_ap_vld;
output  [255:0] arrayidx11_4_promoted65_out;
output   arrayidx11_4_promoted65_out_ap_vld;
output  [255:0] arrayidx11_3_promoted63_out;
output   arrayidx11_3_promoted63_out_ap_vld;
output  [255:0] arrayidx11_2_promoted61_out;
output   arrayidx11_2_promoted61_out_ap_vld;
output  [255:0] arrayidx11_1_promoted59_out;
output   arrayidx11_1_promoted59_out_ap_vld;
output  [255:0] arrayidx82_promoted57_out;
output   arrayidx82_promoted57_out_ap_vld;

reg ap_idle;
reg in_stream_TREADY;
reg[255:0] arrayidx11_23_promoted103_out;
reg arrayidx11_23_promoted103_out_ap_vld;
reg[255:0] arrayidx11_22_promoted101_out;
reg arrayidx11_22_promoted101_out_ap_vld;
reg[255:0] arrayidx11_21_promoted99_out;
reg arrayidx11_21_promoted99_out_ap_vld;
reg[255:0] arrayidx11_20_promoted97_out;
reg arrayidx11_20_promoted97_out_ap_vld;
reg[255:0] arrayidx11_19_promoted95_out;
reg arrayidx11_19_promoted95_out_ap_vld;
reg[255:0] arrayidx11_18_promoted93_out;
reg arrayidx11_18_promoted93_out_ap_vld;
reg[255:0] arrayidx11_17_promoted91_out;
reg arrayidx11_17_promoted91_out_ap_vld;
reg[255:0] arrayidx11_16_promoted89_out;
reg arrayidx11_16_promoted89_out_ap_vld;
reg[255:0] arrayidx11_15_promoted87_out;
reg arrayidx11_15_promoted87_out_ap_vld;
reg[255:0] arrayidx11_14_promoted85_out;
reg arrayidx11_14_promoted85_out_ap_vld;
reg[255:0] arrayidx11_13_promoted83_out;
reg arrayidx11_13_promoted83_out_ap_vld;
reg[255:0] arrayidx11_12_promoted81_out;
reg arrayidx11_12_promoted81_out_ap_vld;
reg[255:0] arrayidx11_11_promoted79_out;
reg arrayidx11_11_promoted79_out_ap_vld;
reg[255:0] arrayidx11_10_promoted77_out;
reg arrayidx11_10_promoted77_out_ap_vld;
reg[255:0] arrayidx11_9_promoted75_out;
reg arrayidx11_9_promoted75_out_ap_vld;
reg[255:0] arrayidx11_8_promoted73_out;
reg arrayidx11_8_promoted73_out_ap_vld;
reg[255:0] arrayidx11_7_promoted71_out;
reg arrayidx11_7_promoted71_out_ap_vld;
reg[255:0] arrayidx11_6_promoted69_out;
reg arrayidx11_6_promoted69_out_ap_vld;
reg[255:0] arrayidx11_5_promoted67_out;
reg arrayidx11_5_promoted67_out_ap_vld;
reg[255:0] arrayidx11_4_promoted65_out;
reg arrayidx11_4_promoted65_out_ap_vld;
reg[255:0] arrayidx11_3_promoted63_out;
reg arrayidx11_3_promoted63_out_ap_vld;
reg[255:0] arrayidx11_2_promoted61_out;
reg arrayidx11_2_promoted61_out_ap_vld;
reg[255:0] arrayidx11_1_promoted59_out;
reg arrayidx11_1_promoted59_out_ap_vld;
reg[255:0] arrayidx82_promoted57_out;
reg arrayidx82_promoted57_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln42_fu_288_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire   [255:0] state_fu_300_p1;
wire    ap_loop_init;
wire   [4:0] i_2_load_fu_285_p1;
reg   [4:0] i_fu_126;
wire   [4:0] add_ln42_fu_294_p2;
reg   [4:0] ap_sig_allocacmp_i_2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_191;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_126 = 5'd0;
#0 ap_done_reg = 1'b0;
end

poseidon_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln42_fu_288_p2 == 1'd0)) begin
            i_fu_126 <= add_ln42_fu_294_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_126 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_126;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd10) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_10_promoted77_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_10_promoted77_out = 'bx;
        end else begin
            arrayidx11_10_promoted77_out = 'bx;
        end
    end else begin
        arrayidx11_10_promoted77_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd10) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_10_promoted77_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_10_promoted77_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd11) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_11_promoted79_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_11_promoted79_out = 'bx;
        end else begin
            arrayidx11_11_promoted79_out = 'bx;
        end
    end else begin
        arrayidx11_11_promoted79_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd11) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_11_promoted79_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_11_promoted79_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd12) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_12_promoted81_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_12_promoted81_out = 'bx;
        end else begin
            arrayidx11_12_promoted81_out = 'bx;
        end
    end else begin
        arrayidx11_12_promoted81_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd12) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_12_promoted81_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_12_promoted81_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd13) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_13_promoted83_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_13_promoted83_out = 'bx;
        end else begin
            arrayidx11_13_promoted83_out = 'bx;
        end
    end else begin
        arrayidx11_13_promoted83_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd13) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_13_promoted83_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_13_promoted83_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd14) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_14_promoted85_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_14_promoted85_out = 'bx;
        end else begin
            arrayidx11_14_promoted85_out = 'bx;
        end
    end else begin
        arrayidx11_14_promoted85_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd14) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_14_promoted85_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_14_promoted85_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd15) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_15_promoted87_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_15_promoted87_out = 'bx;
        end else begin
            arrayidx11_15_promoted87_out = 'bx;
        end
    end else begin
        arrayidx11_15_promoted87_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd15) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_15_promoted87_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_15_promoted87_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd16) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_16_promoted89_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_16_promoted89_out = 'bx;
        end else begin
            arrayidx11_16_promoted89_out = 'bx;
        end
    end else begin
        arrayidx11_16_promoted89_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd16) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_16_promoted89_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_16_promoted89_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd17) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_17_promoted91_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_17_promoted91_out = 'bx;
        end else begin
            arrayidx11_17_promoted91_out = 'bx;
        end
    end else begin
        arrayidx11_17_promoted91_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd17) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_17_promoted91_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_17_promoted91_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd18) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_18_promoted93_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_18_promoted93_out = 'bx;
        end else begin
            arrayidx11_18_promoted93_out = 'bx;
        end
    end else begin
        arrayidx11_18_promoted93_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd18) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_18_promoted93_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_18_promoted93_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd19) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_19_promoted95_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_19_promoted95_out = 'bx;
        end else begin
            arrayidx11_19_promoted95_out = 'bx;
        end
    end else begin
        arrayidx11_19_promoted95_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd19) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_19_promoted95_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_19_promoted95_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd1) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_1_promoted59_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_1_promoted59_out = 'bx;
        end else begin
            arrayidx11_1_promoted59_out = 'bx;
        end
    end else begin
        arrayidx11_1_promoted59_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_1_promoted59_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_1_promoted59_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd20) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_20_promoted97_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_20_promoted97_out = 'bx;
        end else begin
            arrayidx11_20_promoted97_out = 'bx;
        end
    end else begin
        arrayidx11_20_promoted97_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd20) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_20_promoted97_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_20_promoted97_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd21) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_21_promoted99_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_21_promoted99_out = 'bx;
        end else begin
            arrayidx11_21_promoted99_out = 'bx;
        end
    end else begin
        arrayidx11_21_promoted99_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd21) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_21_promoted99_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_21_promoted99_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd22) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_22_promoted101_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_22_promoted101_out = 'bx;
        end else begin
            arrayidx11_22_promoted101_out = 'bx;
        end
    end else begin
        arrayidx11_22_promoted101_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd22) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_22_promoted101_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_22_promoted101_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_191)) begin
            arrayidx11_23_promoted103_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_23_promoted103_out = 'bx;
        end else begin
            arrayidx11_23_promoted103_out = 'bx;
        end
    end else begin
        arrayidx11_23_promoted103_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | (~(i_2_load_fu_285_p1 == 5'd22) & ~(i_2_load_fu_285_p1 == 5'd21) & ~(i_2_load_fu_285_p1 == 5'd20) & ~(i_2_load_fu_285_p1 == 5'd19) & ~(i_2_load_fu_285_p1 == 5'd18) & ~(i_2_load_fu_285_p1 == 5'd17) & ~(i_2_load_fu_285_p1 == 5'd16) & ~(i_2_load_fu_285_p1 == 5'd15) & ~(i_2_load_fu_285_p1 == 5'd14) & ~(i_2_load_fu_285_p1 == 5'd13) & ~(i_2_load_fu_285_p1 == 5'd12) & ~(i_2_load_fu_285_p1 == 5'd11) & ~(i_2_load_fu_285_p1 == 5'd10) & ~(i_2_load_fu_285_p1 == 5'd9) & ~(i_2_load_fu_285_p1 == 5'd8) & ~(i_2_load_fu_285_p1 == 5'd7) & ~(i_2_load_fu_285_p1 == 5'd6) & ~(i_2_load_fu_285_p1 == 5'd5) & ~(i_2_load_fu_285_p1 == 5'd4) & ~(i_2_load_fu_285_p1 == 5'd3) & ~(i_2_load_fu_285_p1 == 5'd2) & ~(i_2_load_fu_285_p1 == 5'd1) & ~(i_2_load_fu_285_p1 == 5'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_23_promoted103_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_23_promoted103_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd2) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_2_promoted61_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_2_promoted61_out = 'bx;
        end else begin
            arrayidx11_2_promoted61_out = 'bx;
        end
    end else begin
        arrayidx11_2_promoted61_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd2) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_2_promoted61_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_2_promoted61_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd3) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_3_promoted63_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_3_promoted63_out = 'bx;
        end else begin
            arrayidx11_3_promoted63_out = 'bx;
        end
    end else begin
        arrayidx11_3_promoted63_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd3) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_3_promoted63_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_3_promoted63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd4) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_4_promoted65_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_4_promoted65_out = 'bx;
        end else begin
            arrayidx11_4_promoted65_out = 'bx;
        end
    end else begin
        arrayidx11_4_promoted65_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd4) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_4_promoted65_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_4_promoted65_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd5) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_5_promoted67_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_5_promoted67_out = 'bx;
        end else begin
            arrayidx11_5_promoted67_out = 'bx;
        end
    end else begin
        arrayidx11_5_promoted67_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd5) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_5_promoted67_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_5_promoted67_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd6) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_6_promoted69_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_6_promoted69_out = 'bx;
        end else begin
            arrayidx11_6_promoted69_out = 'bx;
        end
    end else begin
        arrayidx11_6_promoted69_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd6) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_6_promoted69_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_6_promoted69_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd7) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_7_promoted71_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_7_promoted71_out = 'bx;
        end else begin
            arrayidx11_7_promoted71_out = 'bx;
        end
    end else begin
        arrayidx11_7_promoted71_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd7) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_7_promoted71_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_7_promoted71_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd8) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_8_promoted73_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_8_promoted73_out = 'bx;
        end else begin
            arrayidx11_8_promoted73_out = 'bx;
        end
    end else begin
        arrayidx11_8_promoted73_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd8) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_8_promoted73_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_8_promoted73_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd9) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx11_9_promoted75_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx11_9_promoted75_out = 'bx;
        end else begin
            arrayidx11_9_promoted75_out = 'bx;
        end
    end else begin
        arrayidx11_9_promoted75_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd9) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx11_9_promoted75_out_ap_vld = 1'b1;
    end else begin
        arrayidx11_9_promoted75_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((i_2_load_fu_285_p1 == 5'd0) & (icmp_ln42_fu_288_p2 == 1'd0))) begin
            arrayidx82_promoted57_out = state_fu_300_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            arrayidx82_promoted57_out = 'bx;
        end else begin
            arrayidx82_promoted57_out = 'bx;
        end
    end else begin
        arrayidx82_promoted57_out = 'bx;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((i_2_load_fu_285_p1 == 5'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arrayidx82_promoted57_out_ap_vld = 1'b1;
    end else begin
        arrayidx82_promoted57_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln42_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_fu_294_p2 = (ap_sig_allocacmp_i_2 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln42_fu_288_p2 == 1'd0) & (in_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_191 = (~(i_2_load_fu_285_p1 == 5'd22) & ~(i_2_load_fu_285_p1 == 5'd21) & ~(i_2_load_fu_285_p1 == 5'd20) & ~(i_2_load_fu_285_p1 == 5'd19) & ~(i_2_load_fu_285_p1 == 5'd18) & ~(i_2_load_fu_285_p1 == 5'd17) & ~(i_2_load_fu_285_p1 == 5'd16) & ~(i_2_load_fu_285_p1 == 5'd15) & ~(i_2_load_fu_285_p1 == 5'd14) & ~(i_2_load_fu_285_p1 == 5'd13) & ~(i_2_load_fu_285_p1 == 5'd12) & ~(i_2_load_fu_285_p1 == 5'd11) & ~(i_2_load_fu_285_p1 == 5'd10) & ~(i_2_load_fu_285_p1 == 5'd9) & ~(i_2_load_fu_285_p1 == 5'd8) & ~(i_2_load_fu_285_p1 == 5'd7) & ~(i_2_load_fu_285_p1 == 5'd6) & ~(i_2_load_fu_285_p1 == 5'd5) & ~(i_2_load_fu_285_p1 == 5'd4) & ~(i_2_load_fu_285_p1 == 5'd3) & ~(i_2_load_fu_285_p1 == 5'd2) & ~(i_2_load_fu_285_p1 == 5'd1) & ~(i_2_load_fu_285_p1 == 5'd0) & (icmp_ln42_fu_288_p2 == 1'd0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_2_load_fu_285_p1 = ap_sig_allocacmp_i_2;

assign icmp_ln42_fu_288_p2 = ((ap_sig_allocacmp_i_2 == 5'd24) ? 1'b1 : 1'b0);

assign state_fu_300_p1 = in_stream_TDATA[255:0];

endmodule //poseidon_top_poseidon_top_Pipeline_VITIS_LOOP_42_1
